### ISSUE TITLE
ICON image format BUG

### ISSUE THREAD

**Issue by codyliou** [HolonGlobe/PurpleMine2#1]
link image
![image](https://cloud.githubusercontent.com/assets/5194005/6612253/f6048860-c8b3-11e4-9d7e-e59475bf128c.png)

**Comment by mrliptontea** [comment]
Hello there!

Thank you for posting this issue. I'll need more details though, could you describe where exactly it occurs? I don't think it's Redmine's icon, so it's probably a plugin, so I'll need to know which one.

**Comment by codyliou** [comment]
it,s Redmine People plugin
http://redminecrm.com/projects/people

Usability plugin
http://rmplus.pro/
![image](https://cloud.githubusercontent.com/assets/5194005/6631310/8cb0b482-c95e-11e4-98ba-85b014485d3e.png)

Code Highlight plugin
https://github.com/mediatainment/redmine-codebutton
![image](https://cloud.githubusercontent.com/assets/5194005/6631302/77704e5c-c95e-11e4-95bc-f62a21c8256f.png)

**Comment by mrliptontea** [comment]
Thank you!
I'll try and find some universal solution to this problem.

**Comment by mrliptontea** [comment]
Pull changes from the master branch, should be alright now.
