### ISSUE TITLE
I have equal action icons bottom issue form

### ISSUE THREAD

**Issue by JohnBat26** [HolonGlobe/PurpleMine2#10]
I have equal action icons bottom issue form:
![purplemine_equal_icons](https://cloud.githubusercontent.com/assets/732942/7217210/4e03abbc-e624-11e4-8d85-cc540c75667d.png)

**Comment by mrliptontea** [comment]
You need to find out what's causing this on your end because it does not happen with any plugin I have or with the unmodified theme.

**Comment by JohnBat26** [comment]
Sorry. False alarm !
