### ISSUE TITLE
Insert company's logo in header

### ISSUE THREAD

**Issue by lublasco** [HolonGlobe/PurpleMine2#11]
Hi,

is it possible to insert a company logo in the header, as in A1 theme? http://www.redminecrm.com/pages/a1-theme (replacing the redmine logo by the company's logo).

Thanks for the best Redmine theme :)

**Comment by mrliptontea** [comment]
I'll see and think of something :wink:

**Comment by mrliptontea** [comment]
So here it is. If you want to display your company's logo in the header:

1. In `images` create a new folder called `logo`.
2. In that folder insert file `logo.png` and optionally `logo@2x.png`.
3. Now in your [`_custom_variables.scss`](https://github.com/HolonGlobe/PurpleMine2#how-to-customize-it) enable logo by setting `$use-logo: true`.

Useful variables and their defaults, which will help you make it look properly:

```sass
$use-logo:                      false !default;
$use-retina-logo:               false !default;

$header-padding-vertical:       10px !default;
$header-padding-horizontal:     $padding-side !default; // 20px

$logo-image-width:              60px !default;
$logo-image-height:             40px !default;
$logo-position-horizontal:      $header-padding-vertical !default;
$logo-position-vertical:        center !default;
$logo-space:                    floor($header-padding-vertical / 2) !default;
```

Names of the variables should be self-explanatory, please leave a comment If you need some more explanation.

**Comment by lublasco** [comment]
Thank you very much. I'll try this and come back with the feedback.

Cheers!

**Comment by carlittoer** [comment]
Hi, I tried this on redmine 4 with the latest release. Apparently it's not working. 

Can you please confirm?

**Comment by carlittoer** [comment]
When I change the required files, the npm watcher throws an error. Is that related?


>> File "src/sass/application.scss" changed.
Loading "sass.js" tasks...ERROR
>> SyntaxError: Unexpected token (
Warning: Task "sass" not found. Use --force to continue.

**Comment by carlittoer** [comment]
Sorry that was my node version. 

Thanks.
