### ISSUE TITLE
Contextual menu does not appear always in issue subject

### ISSUE THREAD

**Issue by lublasco** [HolonGlobe/PurpleMine2#12]
The contectual menu only appears when right-clicking just above or below the task subject link, but not to the right of its link, that is much more easy to click, because you usually have more space. 

I think the problem is the task link is actually prolonging to the right in the background.

This problem does not happen in other columns, only in the subject column (issue list).

Thanks!!

**Comment by mrliptontea** [comment]
The intention was to make it easier to go to the issue page, but I admit that this is not very useful. The f ix is going right away.
