### ISSUE TITLE
stuff_to_do plugin management page is collapsed

### ISSUE THREAD

**Issue by Wmn** [HolonGlobe/PurpleMine2#13]
Management page of [stuff to do plugin](/SandStormIT/stuff_to_do_plugin) is collapsed:
![purplemine2-stuff-to-do](https://cloud.githubusercontent.com/assets/3067077/8666856/f512e228-2a18-11e5-80bf-cee9e15d75f5.png)
In Alternate stock redmine theme everything is fine:
![alternate-stuff-to-do](https://cloud.githubusercontent.com/assets/3067077/8666919/bd13b5b8-2a19-11e5-8eb7-0ce6bdec6b9f.png)
I managed to get it fixed by adding this style:
```css
#main.nosidebar div#content {
  width: 98%;
}
```
Now it looks like this:
![purplemine2-stuff-to-do-fixed](https://cloud.githubusercontent.com/assets/3067077/8667037/81aa65ba-2a1b-11e5-8c03-c391b0507550.png)

May be there is more proper fix.

**Comment by mrliptontea** [comment]
This plugin's CSS added `float` to header's `h1` which caused it to collapse as its only children were floating. The fix also probably prevented issues with some other plugins, so thanks :wink:
