### ISSUE TITLE
Remove overflow hidden for #content

### ISSUE THREAD

**Issue by shawndibble** [HolonGlobe/PurpleMine2#15]
I understand that you use overflow hidden for the #content so that it doesn't get wrapped around the sidebar. Unfortunately if you have anything that tries to go beyond the content window, it disappears/gets cut off. 

IMO, an alternative solution would be to change #content from:

#content {
    padding: 20px;
    overflow: hidden;
}

to 

#content {
    padding: 20px;
    position: absolute;
    margin-left: 270px;
}

The only problem to this is that with the toggle sidebar javascript, you would need to have that margin left change between 270px and 0px.

**Comment by mrliptontea** [comment]
I've been thinking about just that some time ago. But `position: absolute` is not a solution to layout-related problems because it breaks the layout.

Recently I had an idea of using flexbox in the theme. The [browser support](http://caniuse.com/#search=flexbox) is pretty good. Maybe I'll work on it this weekend.

**Comment by shawndibble** [comment]
Great idea. I just adjusted the theme to use flexbox. If you want to know how I adjusted my setup:

#main {
    display: flex; <-- added
    position: relative;
}
#sidebar {
    width: 229px;
    padding: 20px;
    align-items: stretch; <-- added
    float: left;
}
#content {
    padding: 20px;
    align-items: stretch; <-- added
    width: 100%; <-- added
    overflow: hidden; <-- removed
}

**Comment by mrliptontea** [comment]
`align-items: stretch` is the default so you don't need it, and in your code it has no effect because it should be applied to the flex container (`#main`).

In order to make it work you should use this:

```css
#main {
    overflow: visible;
    display: flex;
}

#content {
    flex: 1;
}
```

**Comment by mrliptontea** [comment]
@shawndibble you might want to pull latest master version because `.tabs` could have break the layout as it had set `width: 2000px` to prevent wrapping tabs. Flexbox is now default, and this issue is also fixed by using flex.
