### ISSUE TITLE
nowrap pushes issue page way over.

### ISSUE THREAD

**Issue by shawndibble** [HolonGlobe/PurpleMine2#16]
_icons.scss line 769, has white-space: nowrap;

Unfortunately if you are on an issue page and you link to an external URL that happens to be really long, it will push the page far out. Actually had someone confused b/c they couldn't see the edit buttons any more.

Anyways, I have had to remove that line from my file for now as I couldn't overwrite it in the _custom-variables.scss file.

**Comment by mrliptontea** [comment]
You're right! And making the page wider than the browser's window is one of the cons of flexbox.
