### ISSUE TITLE
Artefact at sorting header 

### ISSUE THREAD

**Issue by JohnBat26** [HolonGlobe/PurpleMine2#2]
Hello.
Thanks for very nice theme!
But I have artefact at tables header:
![redmine_table_sortings_artefact](https://cloud.githubusercontent.com/assets/732942/7066695/d91852a6-decd-11e4-8d66-31fc0f914bf4.png)

**Comment by mrliptontea** [comment]
Hi there!
You're welcome :wink: 

This is probably some plugin's fault. Tell me if you are using any.

Can you inspect this element (right click on it → *Inspect element* or something like that) and tell me from what stylesheet (CSS file) this background is coming from?

**Comment by JohnBat26** [comment]
I've resolved  this issue :)
~~~
th .asc  { /* background-image: url(../../../images/sort_asc.png); */ }
~~~

From redmine_knowledgebase plugin (knowledgebase.css)

**Comment by mrliptontea** [comment]
Alrighty then :smiley:

I'll figure some workaround out later to prevent this in future.
