### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [HolonGlobe/PurpleMine2#258]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by mrliptontea** [comment]
Hello,

As much as I'd like to keep it alive, I simply don't have the time to maintain it anymore, also I stopped using Redmine years ago but tried to keep the theme working with newer versions whenever I could find the time for it.

Any help would be appreciated, and active maintainers even more so!
