### ISSUE TITLE
Do closed task more appreciable

### ISSUE THREAD

**Issue by JohnBat26** [HolonGlobe/PurpleMine2#3]
Hello again :)
Could you do closed tasks more appreciable ? 
I attached screenshot with current situation
Strikethrough line almost invisible.
Thanks in advance,
![purplemine_closed_tasks](https://cloud.githubusercontent.com/assets/732942/7131861/86b6d056-e28c-11e4-82ce-1d302a13528c.png)

**Comment by mrliptontea** [comment]
I think fbae203 should do it :wink:
