### ISSUE TITLE
Add tablesorter in issue form for subtask and relations tasks

### ISSUE THREAD

**Issue by JohnBat26** [HolonGlobe/PurpleMine2#4]
It would be nice add tablesorter  in issue form for subtask and relations tasks.

Example: https://github.com/artembeloglazov/redmine-subtask-tablesorter

**Comment by mrliptontea** [comment]
I think it would be best to make it as a plugin.

**Comment by JohnBat26** [comment]
Ready !
https://github.com/JohnBat26/redmine_issues_sortings

**Comment by mrliptontea** [comment]
Great :+1:
