### ISSUE TITLE
Need to add a default style for custom trackers

### ISSUE THREAD

**Issue by JohnBat26** [HolonGlobe/PurpleMine2#5]
If user add several custom trackers, then it shows without pretty style. See attached screenshot:
![purplemine_style_for_custom_trackers](https://cloud.githubusercontent.com/assets/732942/7144147/2d8bda5c-e2ec-11e4-8852-30ca5b182b13.png)

I propose to make some default style for all user trackers

**Comment by JohnBat26** [comment]
Or maybe generate styles for custom trackers dynamically ?

**Comment by mrliptontea** [comment]
How many trackers are we talking about?

Dynamically generated colors are not always beautiful, so I think it's best to have them hard coded, so if it's not too many, I can add more colors. And of course I'll make the default color.

**Comment by JohnBat26** [comment]
We have 17 trackers at all.
Сan  make the colors for 20 trackers?

**Comment by mrliptontea** [comment]
It will be hard to avoid similarities, but I think I have an idea how to make it easier to add new colors just by playing with variables.

Stay tuned.

**Comment by mrliptontea** [comment]
Please see d220db1 for proposed solution.

**Comment by JohnBat26** [comment]
ok :+1:
