### ISSUE TITLE
Disable styles from  sidebar_hide plugin for PurpleMine2 theme

### ISSUE THREAD

**Issue by JohnBat26** [HolonGlobe/PurpleMine2#7]
Redmine community has very useful plugin: https://www.redmine.org/plugins/sidebar_hide
It add styles for hide sidebar. Sidebar_hide styles  should be removed from the PurpleMine2 theme, 
because PurpleMine2 has similar functionality.
![purplemine_and_sidebar_hide_plugin](https://cloud.githubusercontent.com/assets/732942/7154544/cb12628c-e35f-11e4-9e20-61016a85cb8b.png)

**Comment by mrliptontea** [comment]
I am aware of this plugin, but it does not fit PurpleMine2 since in it by default the sidebar is on the left and plugin's button appears always on the right. And I like storing the state of the sidebar in localStorage better than cookies.

So if you use PurpleMine, this plugin is redundant.

**Comment by JohnBat26** [comment]
Yes, but other users can select other themes, and sidebar_hide styles needs for these themes.
I want disable sidebar_hide styles only for PurpleMine2 and leave enabled in others themes.

**Comment by mrliptontea** [comment]
It can be disabled by setting `$enable-sidebar-toggler` variable to `false` :wink:

**Comment by JohnBat26** [comment]
where ?

**Comment by mrliptontea** [comment]
You can find it in `src/sass/_variables.scss`.

It's best to create your own file e.g. `src/sass/_custom-variables.scss` and import it in `application.scss` like this:

```scss
@import "custom-variables";
@import "variables";
```

In this your file just type:

```scss
$enable-sidebar-toggler: false;
```

Then rebuild stylesheets by running `grunt css` and that should do it.

**Comment by JohnBat26** [comment]
:+1:
