### ISSUE TITLE
Remove the wrapping from the top menu

### ISSUE THREAD

**Issue by JohnBat26** [HolonGlobe/PurpleMine2#8]
Can you  remove the wrapping from the top menu ? See screenshot:
![purplemine_top_menu_folding](https://cloud.githubusercontent.com/assets/732942/7188012/57792738-e47d-11e4-8a6b-c383c076ca8d.png)

**Comment by mrliptontea** [comment]
But then you'll lose sight of some links (they will be cut out)?

**Comment by JohnBat26** [comment]
Hmm. May be create additional popup menu at right side of top menu?
and this popup menu will consist of second line menu items.

**Comment by mrliptontea** [comment]
I can't think of anything better. I imagine it would work by setting fixed height of the menu and there would be a button for extending the menu to access hidden links. By default, this feature will be disabled, as not everyone has the top menu so wide.

And by the way: check the settings for plugins which have added additional links to this menu. Maybe some of them can be moved to the main menu bar, so they'll make the top one shorter. For example, [Backlogs](http://www.redminebacklogs.net/) plugin does have such option.

**Comment by mrliptontea** [comment]
There are two variables for you to set:

- `$top-menu-collapse` must be set to `true` to enable this feature,
- `$top-menu-collapse-breakpoint` determines the maximum screen width in which expanding button will be shown (so users with a wide screen resolution won't be bothered with this). Default is 1200px

**Comment by JohnBat26** [comment]
You are awersome! :+1:  :+1:  :+1:
