### ISSUE TITLE
Remove the wrapping from the project menu :)

### ISSUE THREAD

**Issue by JohnBat26** [HolonGlobe/PurpleMine2#9]
And can you remove wrapping from project menu ? ;) Similarly with  #8 
![purplemine_project_menu_wrapping](https://cloud.githubusercontent.com/assets/732942/7201748/78d18ccc-e513-11e4-82f3-3731552aa608.png)

**Comment by mrliptontea** [comment]
hehe, no problem

**Comment by JohnBat26** [comment]
Brilliant ! :+1: 
Thanks!
